# Generated by Django 4.2.4 on 2023-11-18 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], default='H', max_length=1)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=50)),
                ('tipo_organizacion', models.CharField(max_length=50)),
                ('descripcion_org', models.TextField()),
                ('email_organizacion', models.EmailField(max_length=254)),
                ('telefono_organizacion', models.DecimalField(decimal_places=0, max_digits=10)),
                ('direccion', models.CharField(max_length=50)),
                ('sitio_web', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado_seguimiento', models.CharField(max_length=50)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.usuario')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vacuna', models.CharField(max_length=50)),
                ('nombre_veterinario', models.CharField(max_length=50)),
                ('fecha_proximo_control', models.DateField()),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.usuario')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=50)),
                ('nombre_comuna', models.CharField(max_length=50)),
                ('organizaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='FotoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto', models.URLField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_salud', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.usuario')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='CitaAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado_cita', models.CharField(max_length=50)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.usuario')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.mascota')),
            ],
        ),
    ]
