# Generated by Django 4.2.4 on 2023-12-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptar', '0003_organizacion_password_org_alter_mascota_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotomascota',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='fotos/'),
        ),
    ]
