# Generated by Django 4.2.4 on 2023-12-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptar', '0004_fotomascota_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('actividad_economica', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.mascota')),
            ],
        ),
    ]
