# Generated by Django 4.2.4 on 2023-12-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptar', '0010_alter_mascota_foto_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto_mascota',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
