# Generated by Django 4.2.4 on 2023-12-30 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adoptar', '0012_alter_seguimientoadopcion_adoptante_colecta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovacuna',
            name='adoptante',
        ),
        migrations.RemoveField(
            model_name='registrovacuna',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='registrovacuna',
            name='fecha_proximo_control',
        ),
        migrations.RemoveField(
            model_name='registrovacuna',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='registrovacuna',
            name='nombre_veterinario',
        ),
        migrations.CreateModel(
            name='SeguimientoEstadoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_mascota_mia', models.ImageField(blank=True, null=True, upload_to='fotos_mascota_mia')),
                ('fecha_vacuna', models.DateField()),
                ('descripcion_estado_salud', models.TextField()),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.mascota')),
                ('vacuna_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptar.registrovacuna')),
            ],
        ),
    ]
