# Generated by Django 4.2.4 on 2023-12-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptar', '0013_remove_registrovacuna_adoptante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadosalud',
            name='adoptante',
        ),
        migrations.RemoveField(
            model_name='estadosalud',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='estadosalud',
            name='mascota',
        ),
    ]
