# Generated by Django 4.2.4 on 2023-12-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptar', '0014_remove_estadosalud_adoptante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadosalud',
            name='estado_salud',
        ),
        migrations.AddField(
            model_name='estadosalud',
            name='descripcion',
            field=models.CharField(default='valor_predeterminado', max_length=255),
        ),
    ]
