# Generated by Django 4.2.4 on 2024-01-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptar', '0016_sede_mascota_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecta',
            name='recaudado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='colecta',
            name='meta',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='seguimientoestadosalud',
            name='foto_mascota_mia',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
